import re
import logging
from typing import Dict, Any, List

logger = logging.getLogger("reporting.report_validator")

class ReportValidator:

    """
    Validates reports generated by the Intelligent Report Engine.
    Ensures zero placeholder usage, no hardcoded metrics, and complete citation grounding.
    """
    @staticmethod
    def validate_report(report_content: str, shared_state: Dict[str, Any]) -> Dict[str, Any]:
        issues = []
        status = "PASS"
        
        # 1. Check for placeholder text / simulated patterns
        placeholders = [
            r"\[employee name\]", r"\[insert.*\]", r"lorem ipsum", r"placeholder", r"simulated", r"mock analysis"
        ]
        for p in placeholders:
            if re.search(p, report_content, re.IGNORECASE):
                issues.append(f"Detected placeholder or simulated pattern: '{p}'")
                status = "FAIL"

        # 2. Check for assumed domain (Cloud Engineering) unless in query or dataset
        query = shared_state.get("user_query", "").lower()
        if "cloud engineer" in report_content.lower() or "cloud engineering" in report_content.lower():
            if "cloud engineer" not in query and "cloud engineering" not in query:
                has_cloud_data = False
                util_results = shared_state.get("utilization_results", {})
                if isinstance(util_results, dict):
                    has_cloud_data = any("cloud" in str(v).lower() for v in util_results.values())
                if not has_cloud_data:
                    issues.append("Detected assumed domain 'Cloud Engineering' which is not in query or data.")
                    status = "FAIL"

        # 3. Check for prompt leakage or instructions
        instruction_patterns = [
            r"you are a (?:senior|professional|elite|strategic|department|talent|risk|data|consultant|partner|analyst|briefing|briefer|strategist|auditor)",
            r"output only",
            r"do not include",
            r"do not invent",
            r"strictly use the",
            r"structured data:",
            r"here is the narrative"
        ]
        for ip in instruction_patterns:
            if re.search(ip, report_content, re.IGNORECASE):
                issues.append(f"Detected leaked prompt instruction pattern: '{ip}'")
                status = "FAIL"

        # 4. Check for duplicate narratives (repeated paragraphs or sentences)
        paragraphs = [p.strip() for p in report_content.split("\n\n") if p.strip()]
        seen_paragraphs = set()
        for p in paragraphs:
            if len(p) > 60:
                std_p = re.sub(r"\s+", " ", p).lower()
                if std_p in seen_paragraphs:
                    issues.append(f"Detected duplicate narrative paragraph: '{p[:50]}...'")
                    status = "FAIL"
                else:
                    seen_paragraphs.add(std_p)

        # 5. Check for empty sections
        lines = [line.strip() for line in report_content.split("\n")]
        for idx, line in enumerate(lines):
            if line.startswith("#"):
                next_content = ""
                for j in range(idx + 1, len(lines)):
                    if lines[j]:
                        next_content = lines[j]
                        break
                if next_content.startswith("#") or not next_content:
                    issues.append(f"Detected empty report section under heading: '{line}'")
                    status = "FAIL"

        # 6. Check for hardcoded metrics
        if "412" in report_content and "412" not in query:
            issues.append("Detected hardcoded metric '412' which is not in real dataset.")
            status = "FAIL"
                
        if "94.2%" in report_content and "94.2" not in query:
            issues.append("Detected hardcoded metric '94.2%' which does not match computed utilization.")
            status = "FAIL"
            
        if "14 FTE" in report_content and "14" not in query:
            issues.append("Detected hardcoded metric '14 FTE shortage' which is not in real dataset.")
            status = "FAIL"

        # 7. Check for evidence elements (only if recommendations block exists)
        required_evidence_fields = [
            "Generated By", "Supporting Agent", "Supporting Tool", "Dataset",
            "Rows Processed", "Confidence", "Execution Timestamp", "Validation Status"
        ]
        
        recs_in_report = "## Recommendations" in report_content or "### Recommendation" in report_content
        if recs_in_report:
            missing_fields = [f for f in required_evidence_fields if f not in report_content]
            if missing_fields:
                issues.append(f"Missing required evidence fields in recommendations block: {missing_fields}")
                status = "FAIL"

        # 8. Check if sections correspond to executed agents
        executed_agents = [log["agent_name"] for log in shared_state.get("execution_log", []) if log["status"] == "success"]
        
        if "## forecast" in report_content.lower() and "ForecastAgent" not in executed_agents:
            issues.append("Report contains Forecast section but ForecastAgent was not executed successfully.")
            status = "FAIL"
                
        if "## utilization" in report_content.lower() and "UtilizationAgent" not in executed_agents:
            issues.append("Report contains Utilization section but UtilizationAgent was not executed successfully.")
            status = "FAIL"

        # 9. Report Consistency Checks (Enhancement 11)
        title_line = report_content.split("\n")[0] if report_content else ""
        is_employee = "Employee Lookup" in title_line
        is_forecast = "Capacity Forecasting" in title_line
        is_recs = "Strategic Recommendation" in title_line
        is_util = "Workforce Utilization" in title_line
        
        if is_employee:
            for kw in ["## future demand", "## hiring forecast", "## scenario analysis", "## current capacity"]:
                if kw in report_content.lower():
                    issues.append(f"Employee report contains unrelated enterprise forecast section: '{kw}'")
                    status = "FAIL"
        
        elif is_forecast:
            for kw in ["## employee results", "## project assignment", "### employee profile details"]:
                if kw in report_content.lower():
                    issues.append(f"Forecast report contains unrelated employee profile section: '{kw}'")
                    status = "FAIL"
                    
        elif is_recs:
            if report_content.lower().count("## executive summary") > 1:
                issues.append("Recommendation report contains duplicate Executive Summary sections.")
                status = "FAIL"
            for kw in ["## employee results", "## project assignment", "## future demand", "## hiring forecast"]:
                if kw in report_content.lower():
                    issues.append(f"Recommendation report contains unrelated section: '{kw}'")
                    status = "FAIL"

        elif is_util:
            for kw in ["## employee results", "## project assignment", "## future demand", "## hiring forecast"]:
                if kw in report_content.lower():
                    issues.append(f"Utilization report contains unrelated section: '{kw}'")
                    status = "FAIL"

        result = {
            "status": status,
            "checks": [
                "Placeholders check",
                "Assumed domain check",
                "Prompt leakage check",
                "Duplicate narrative check",
                "Empty sections check",
                "Grounded metrics check",
                "Lineage block check",
                "Agent alignment check",
                "Consistency check"
            ],
            "issues": issues
        }
        logger.info(f"[ReportValidator] Validation Result: {status} | Issues: {issues} | Content Length: {len(report_content)} chars")
        return result
